SESTEC/GISWeb/Controllers/AnaliseRiscoController.cs
using GISCore.Business.Abstract;
using GISModel.DTO.AnaliseRisco;
using GISModel.DTO.Shared;
using GISModel.Entidades;
using Ninject;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GISModel.Enums;

namespace GISWeb.Controllers
{
    public class AnaliseRiscoController : Controller
    {
        #region-Inject
        [Inject]
        public IAtividadesDoEstabelecimentoBusiness AtividadesDoEstabelecimentoBusiness { get; set; }

        [Inject]
        public IEmpresaBusiness EmpresaBusiness { get; set; }

        [Inject]
        public IAtividadeAlocadaBusiness AtividadeAlocadaBusiness { get; set; }


        [Inject]
        public ITipoDeRiscoBusiness TipoDeRiscoBusiness { get; set; }

        [Inject]
        public IAnaliseRiscoBusiness AnaliseRiscoBusiness { get; set; }

        [Inject]
        public IAlocacaoBusiness AlocacaoBusiness { get; set; }

        [Inject]
        public IAdmissaoBusiness AdmissaoBusiness { get; set; }

        [Inject]
        public IEmpregadoBusiness EmpregadoBusiness { get; set; }

        [Inject]
        public IEventoPerigosoBusiness EventoPerigosoBusiness { get; set; }

        [Inject]
        public IPerigoPotencialBusiness PerigoPotencialBusiness { get; set; }

        #endregion

        // GET: AtividadeAlocada
        public ActionResult Novo(string id)
        {

            ViewBag.Analise = new SelectList(AtividadesDoEstabelecimentoBusiness.Consulta, "IDAtividadesDoEstabelecimento", "DescricaoDestaAtividade");

            return View();
        }

        //Lista atividade para executar análise de risco.
        //Ao escolher a atividade abrirá outra caixa listando os riscos e o empregado informa se 
        //está apto a executar a atividade.
        public ActionResult PesquisarAtividadesRiscos(string idEstabelecimento, string idAlocacao)
        {
            ViewBag.Imagens = AtividadesDoEstabelecimentoBusiness.Consulta.Where(p => string.IsNullOrEmpty(p.UsuarioExclusao) && (p.IDEstabelecimento.Equals(idEstabelecimento))).ToList();

            try
            {


                var listaAmbientes = from AL in AtividadeAlocadaBusiness.Consulta.Where(p => string.IsNullOrEmpty(p.UsuarioExclusao) && p.idAlocacao.Equals(idAlocacao)).ToList()
                                     join AR in AnaliseRiscoBusiness.Consulta.Where(p => string.IsNullOrEmpty(p.UsuarioExclusao)).ToList()
                                     on AL.IDAtividadeAlocada equals AR.IDAtividadeAlocada
                                     into ARGroup
                                     from item in ARGroup.DefaultIfEmpty()

                                     join AE in AtividadesDoEstabelecimentoBusiness.Consulta.Where(p => string.IsNullOrEmpty(p.UsuarioExclusao)).ToList()
                                     on AL.idAtividadesDoEstabelecimento equals AE.IDAtividadesDoEstabelecimento
                                     into AEGroup
                                     from item0 in AEGroup.DefaultIfEmpty()

                                     join TR in TipoDeRiscoBusiness.Consulta.Where(p => string.IsNullOrEmpty(p.UsuarioExclusao)).ToList()
                                     on item0.IDAtividadesDoEstabelecimento equals TR.idAtividadesDoEstabelecimento
                                     into TRGroup
                                     from item1 in TRGroup.DefaultIfEmpty()

                                     select new AnaliseRiscosViewModel
                                     {
                                         DescricaoAtividade = AL.AtividadesDoEstabelecimento.DescricaoDestaAtividade,
                                         //Riscos = item1.PerigoPotencial.DescricaoEvento,
                                         //FonteGeradora = item1.FonteGeradora,
                                         AlocaAtividade = (item == null ? false : true),
                                         Conhecimento = item.Conhecimento,
                                         BemEstar = item.BemEstar,



                                     };


                List<AnaliseRiscosViewModel> lAtividadesRiscos = listaAmbientes.ToList();



                AtividadesDoEstabelecimento oIDRiscosDoEstabelecimento = AtividadesDoEstabelecimentoBusiness.Consulta.FirstOrDefault(p => p.IDEstabelecimento.Equals(idEstabelecimento));
                if (oIDRiscosDoEstabelecimento == null)
                {
                    return Json(new { resultado = new RetornoJSON() { Alerta = "Atividades de Riscos não encontrada." } });
                }
                else
                {
                    return Json(new { data = RenderRazorViewToString("SalvarAnaliseRisco", lAtividadesRiscos), Contar = lAtividadesRiscos.Count() });
                }
            }
            catch (Exception ex)
            {
                if (ex.GetBaseException() == null)
                {
                    return Json(new { resultado = new RetornoJSON() { Erro = ex.Message } });
                }
                else
                {
                    return Json(new { resultado = new RetornoJSON() { Erro = ex.GetBaseException().Message } });
                }
            }

        }


        public ActionResult SalvarAnaliseRisco(string idEstabelecimento, string idAlocacao)
        {

            ViewBag.EventoPerigoso = new SelectList(EventoPerigosoBusiness.Consulta.Where(p => string.IsNullOrEmpty(p.UsuarioExclusao)).ToList(), "IDEventoPerigoso", "Descricao");

            ViewBag.PerigoPotencial = new SelectList(PerigoPotencialBusiness.Consulta.Where(p => string.IsNullOrEmpty(p.UsuarioExclusao)).ToList(), "IDPerigoPotencial", "DescricaoEvento");



            var ListaAmbientes = from AL in AtividadeAlocadaBusiness.Consulta.Where(p => string.IsNullOrEmpty(p.UsuarioExclusao) && p.idAlocacao.Equals(idAlocacao)).ToList()
                                 join AR in AnaliseRiscoBusiness.Consulta.Where(p => string.IsNullOrEmpty(p.UsuarioExclusao)).ToList()
                                 on AL.IDAtividadeAlocada equals AR.IDAtividadeAlocada
                                 into ARGroup
                                 from item in ARGroup.DefaultIfEmpty()

                                 join AE in AtividadesDoEstabelecimentoBusiness.Consulta.Where(p => string.IsNullOrEmpty(p.UsuarioExclusao)).ToList()
                                 on AL.idAtividadesDoEstabelecimento equals AE.IDAtividadesDoEstabelecimento
                                 into AEGroup
                                 from item2 in AEGroup.DefaultIfEmpty()

                                 join TR in TipoDeRiscoBusiness.Consulta.Where(p => string.IsNullOrEmpty(p.UsuarioExclusao)).ToList()
                                 on item2.IDAtividadesDoEstabelecimento equals TR.idAtividadesDoEstabelecimento
                                 into TRGroup
                                 from item3 in TRGroup.DefaultIfEmpty()


                                 select new AnaliseRiscosViewModel
                                 {
                                     //DescricaoAtividade = item.AtividadeAlocada.AtividadesDoEstabelecimento.DescricaoDestaAtividade,
                                     //Riscos = item.AtividadeAlocada.AtividadesDoEstabelecimento.EventoPerigoso.Descricao,
                                     FonteGeradora = item3.FonteGeradora,
                                     IDAmissao = AL.Alocacao.Admissao.IDAdmissao,
                                     Imagem = AL.Alocacao.Admissao.Imagem,
                                     Riscos = item3.EventoPerigoso.Descricao,
                                     DescricaoAtividade = item2.DescricaoDestaAtividade,
                                     IDAtividadeAlocada = AL.IDAtividadeAlocada,
                                     Conhecimento = item == null ? false : true,
                                     BemEstar = item == null ? false : true,
                                     PossiveisDanos = item3.PossiveisDanos.DescricaoDanos,
                                     //IDEventoPerigoso = item?.IDEventoPerigoso ?? null,
                                     //IDPerigoPotencial=item? .IDPerigoPotencial ?? null,
                                     //Conhecimento = item?.Conhecimento ?? false,
                                     //BemEstar = item?.BemEstar ?? false,
                                     IDAtividadeEstabelecimento = AL.AtividadesDoEstabelecimento.IDAtividadesDoEstabelecimento,
                                     imagemEstab = AL.AtividadesDoEstabelecimento.Imagem,
                                     AlocaAtividade = item == null ? false : true
                                 };


            List<AnaliseRiscosViewModel> lAtividadesRiscos = ListaAmbientes.ToList();

            ViewBag.Risco = ListaAmbientes.ToList();

            var Emp = from Adm in AdmissaoBusiness.Consulta.Where(p => string.IsNullOrEmpty(p.UsuarioExclusao)).ToList()
                      join Aloc in AlocacaoBusiness.Consulta.Where(p => string.IsNullOrEmpty(p.UsuarioExclusao)).ToList()
                      on Adm.IDAdmissao equals Aloc.IdAdmissao
                      join Empre in EmpregadoBusiness.Consulta.Where(p => string.IsNullOrEmpty(p.UsuarioExclusao)).ToList()
                      on Adm.IDEmpregado equals Empre.IDEmpregado
                      join Firm in EmpresaBusiness.Consulta.Where(p => string.IsNullOrEmpty(p.UsuarioExclusao)).ToList()
                      on Adm.IDEmpresa equals Firm.IDEmpresa
                      where Aloc.IDAlocacao.Equals(idAlocacao)
                      select new Admissao()
                      {
                          DataAdmissao = Adm.DataAdmissao,
                          Empresa = new Empresa()
                          {
                              NomeFantasia = Firm.NomeFantasia

                          },

                          Empregado = new Empregado()

SESTEC/GISWeb/Views/AnaliseRisco/SalvarAnaliseRisco.cshtml
@using GISModel.Entidades
@using GISModel.DTO.AnaliseRisco
@model GISModel.Entidades.AnaliseRisco

<div class="row">
    <div class="col-xs-12">
        <h3 class="header smaller lighter blue">
            Análise de Risco
            <a href="" class="btn btn-white btn-info btn-bold" style="float: right; margin-top: -2px;">
                <i class="ace-icon fa fa-plus bigger-120 blue"></i>
                Visulizar Análise de Risco
            </a>
        </h3>
    </div>
</div>
@foreach (var oEmp in ViewBag.Emp)
{
    @*<img src="/Images/AdmissaoImagens/@oEmp.Admissao.IDAdmissao/@oEmp.Admissao.Imagem" alt="Admissao" width="100" />*@

    <div class="row ">
        <div class="col-xs-12 col-sm-12 col-lg-12">
            <div class="col-xs-12 col-sm-12 col-lg-12">
                Empregado:
                @oEmp.Empregado.Nome
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-lg-12">
            <div class="col-xs-12 col-sm-12 col-lg-12">
                Empresa:
                @oEmp.Empresa.NomeFantasia
            </div>
        </div>
    </div>


}

<br /><br />

@if (ViewBag.Risco != null)
{



    foreach (AnaliseRiscosViewModel item in ViewBag.Risco)
    {
        using (Ajax.BeginForm("SalvarAnaliseRisco", "AnaliseRisco", null, new AjaxOptions { HttpMethod = "POST", OnBegin = "OnBeginCadastrarAnaliseRisco", OnSuccess = "OnSuccessCadastrarAnaliseRisco", }, new { @id = "formCadastroAnaliseRisco", @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()

            <div class="span12" style="border: 2px solid black">

                <div class="row center">
                    <div class="col-xs-12 col-sm-12 col-lg-12">
                        <img src="/Images/AtividadesEstabelecimentoImagens/@item.IDAtividadeEstabelecimento/@item.imagemEstab" alt="Atividade" width="150px" />
                        <div class="col-xs-12 col-sm-12 col-lg-12">
                            Atividade:
                            @item.DescricaoAtividade
                            <input type="hidden" name="AtivEstabID" id="AtivEstabID" value=@item.IDAtividadeEstabelecimento />
                            <input type="hidden" name="idATivAlocada" id="idATivAlocada" value=@item.IDAtividadeAlocada />
                        </div>
                    </div>
                </div>
                <br />
            </div><br />
            <div class="row">


                <div class="col-xs-6 col-sm-6 col-lg-6 center">
                    <div class="span12" style="border: 2px solid black">
                        <div class="form-group">
                            <div class="text center">Riscos:</div>
                            <div class="col-xs-12 col-sm-12">
                                @item.Riscos
                            </div>
                        </div>
                    </div>
                </div>



                <div class="col-xs-6 col-sm-6 col-lg-6 center">
                    <div class="span12" style="border: 2px solid black">
                        <div class="form-group">
                            <div class="text center">Possíveis Danos:</div>
                            <div class="col-xs-12 col-sm-12">
                                @item.PossiveisDanos
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <br />




            <div class="row">
                <div class="col-xs-6 col-sm-6 col-lg-6">
                    <div class="span12" style="border: 2px solid black">
                        <div class="form-group">
                            @Html.LabelFor(d => d.IDEventoPerigoso, new { @class = "form-field-select-3 col-xs-12 col-sm-12 no-padding-right center" })
                            <div class="col-xs-12 col-sm-12 col-lg-12">
                                @Html.DropDownListFor(d => d.IDEventoPerigoso, (SelectList)ViewBag.EventoPerigoso, "Selecione um Evento...", new { @class = "chosen-select form-control tag-input-style", @id = "ddlEvento", @autocomplete = "on" })
                                @Html.ValidationMessageFor(d => d.IDEventoPerigoso, string.Empty, new { @style = "font-size: 10px; color: #a94442;" })

                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-xs-6 col-sm-6 col-lg-6">
                    <div class="span12" style="border: 2px solid black">
                        <div class="form-group">
                            @Html.LabelFor(d => d.IDPerigoPotencial, new { @class = "form-field-select-3 col-xs-12 col-sm-12 no-padding-right center" })
                            <div class="col-xs-12 col-sm-12 col-lg-12">
                                @Html.DropDownListFor(d => d.IDPerigoPotencial, (SelectList)ViewBag.PerigoPotencial, "Selecione um Perigo...", new { @class = "chosen-select form-control tag-input-style", @id = "ddlPerigo", @autocomplete = "on" })
                                @Html.ValidationMessageFor(d => d.IDPerigoPotencial, string.Empty, new { @style = "font-size: 10px; color: #a94442;" })

                            </div>
                        </div>
                    </div>
                </div>
            </div>


            <br />


            <div class="row">

                <div class="col-xs-6 col-sm-6 col-lg-6 center">
                    <div class="span12" style="border: 2px solid black">

                        @{

                            string PossuiOMenu6 = string.Empty;

                            if (item.Conhecimento == Convert.ToBoolean(true))
                            {
                                PossuiOMenu6 = "checked=\" ";
                            }
                            else
                            {
                                PossuiOMenu6 = " ";
                            }
                        }

                        <div class="form-group">
                            <div class="col-xs-12 col-sm-12 col-lg-6 center">
                                <a href="#" class="tooltip-info" onclick="" ; return false;" data-rel="tooltip" title="View">
                                    <span class="green">
                                        <i class="fa fa-smile-o bigger-180"></i>
                                    </span>
                                    <input type="radio" name="ConhecID" id="ConhecID" value="True" @PossuiOMenu6>Conheço a Atividade
                                </a>
                            </div>
                        </div>
                    </div>
                </div>


                <div class="col-xs-6 col-sm-6 col-lg-6 center">

                    @{

                        string PossuiOMenu5 = string.Empty;

                        if (Convert.ToBoolean(item.Conhecimento) == Convert.ToBoolean(false))
                        {
                            PossuiOMenu5 = "checked=\" ";
                        }
                        else
                        {
                            PossuiOMenu5 = " ";
                        }
                    }
                    <div class="span12" style="border: 2px solid black">
                        <div class="form-group">

                            <div class="col-xs-12 col-sm-12 col-lg-6 center">
                                <a href="#" class="tooltip-info" onclick="" ; return false;" data-rel="tooltip" title="View">
                                    <span class="red">
                                        <i class="fa fa-frown-o bigger-180"></i>
                                    </span>
                                    <input type="radio" name="ConhecID" id="ConhecID" value="False" @PossuiOMenu5>Não conheço a atividade
                                </a>


                            </div>
                        </div>

                    </div>
                </div>

            </div>
            <br />

            <div class="row">
                <div class="col-xs-6 col-sm-6 col-lg-6 center">
                    <div class="span12" style="border: 2px solid black">
                        <div class="form-group">
                            @{

                                string PossuiOMenu2 = string.Empty;
                                if (item.BemEstar == true)
                                {
                                    PossuiOMenu2 = "checked=\" ";
                                }
                                else
                                {
                                    PossuiOMenu2 = " ";
                                }
                            }

                            <div class="col-xs-12 col-sm-12 col-lg-6 center">
                                <a href="#" class="tooltip-info" onclick="" ; return false;" data-rel="tooltip" title="View">
                                    <span class="green">
                                        <i class="fa fa-smile-o bigger-160"></i>
                                    </span>
                                    <input type="radio" name="BemEstarID" id="BemEstarID" value="True" @PossuiOMenu2>Estou bem!
                                </a>

                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-xs-6 col-sm-6 col-lg-6 center">
                    @{

                        string PossuiOMenu3 = string.Empty;
                        if (item.BemEstar == false)
                        {
                            PossuiOMenu3 = "checked=\" ";
                        }
                        else
                        {
                            PossuiOMenu3 = " ";
                        }
                    }
                    <div class="span12" style="border: 2px solid black">
                        <div class="form-group">
                            <div class="col-xs-12 col-sm-12 col-lg-6 center">
                                <a href="#" class="tooltip-info" onclick="" ; return false;" data-rel="tooltip" title="View">
                                    <span class="red">
                                        <i class="fa fa-frown-o bigger-160"></i>
                                    </span>
                                    <input type="radio" name="BemEstarID" id="BemEstarID" value="False" @PossuiOMenu3>Não estou bem!
                                </a>


                            </div>
                        </div>
                    </div>
                </div>
            </div>



            string PossuiOMenu4 = string.Empty;
            if (item.AlocaAtividade)
            {
                PossuiOMenu4 = "disabled";
            }
            //}
            <br />

            <div class="row">
                <div class="col-xs-12 col-sm-12 col-lg-12">
                    <button type="submit" class="btn btn-primary btn-lg btn-block btn-responsive" id="btnSalvar" @PossuiOMenu4>
                        @*<button class="btn btn-info" id="btnSalvar" type="submit" @PossuiOMenu4>*@
                        <i class="ace-icon fa fa-check bigger-55"></i>
                        Salvar
                    </button>
                </div>
            </div>
            <br />



        }

    }


}
else
{
    <div class="row">
        <div class="col-xs-12">
            <div class="error-container" style="margin: 0;">
                <div class="well">
                    <h4 class="blue" style="margin: 0;">
                        <i class="ace-icon fa fa-slack bigger-110"></i>
                        Nenhum perfil encontrado
                    </h4>
                </div>
            </div>
        </div><!-- /.col -->
    </div>
}





@section Scripts {


    <script src="~/Scripts/Custom/AnaliseRisco/Novo.js"></script>

}

SESTEC/GISWeb/Views/AnaliseRisco/_ListaAtividadesDeRiscos.cshtml
@using GISModel.Entidades
@using GISModel.DTO.AnaliseRisco
@model List<AnaliseRiscosViewModel>


@{
    /**/


    if (Model.Count > 0)
    {

        <div class="row">
            <div class="col-xs-12">
                <div class="clearfix">
                    <div class="pull-right tableTools-container"></div>
                </div>

                <div>
                    <table id="tablePerfisPorMenu" class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <th class="center">
                                    &nbsp;
                                </th>
                                <th>
                                    Ambientes
                                </th>
                                <th>
                                    Riscos
                                </th>
                                <th>
                                    Possíveis Danos
                                </th>
                            </tr>
                        </thead>

                        <tbody>

                            @foreach (AnaliseRiscosViewModel item in Model)
                            {
                            <tr>
                                <td class="center">
                                    <label class="pos-rel">

                                        @{
                                            string PossuiOMenu = string.Empty;
                                            if (item.AlocaAtividade)
                                            {
                                                PossuiOMenu = " checked=\" ";
                                            }
                                        }

                                        <input type="checkbox" onclick="SalvarAtividadeEstabelecimento(this.checked, '@item.IDAtividadeEstabelecimento','@item.IDAlocacao');" @PossuiOMenu class="ace">
                                        <span class="lbl"></span>
                                    </label>
                                </td>
                                <td>
                                    @item.DescricaoAtividade
                                </td>
                                <td>
                                    @item.Riscos
                                </td>
                                <td>
                                    @item.PossiveisDanos
                                </td>



                            </tr>
                            }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    }
    else
    {
        <div class="row">
            <div class="col-xs-12">
                <div class="error-container" style="margin: 0;">
                    <div class="well">
                        <h4 class="blue" style="margin: 0;">
                            <i class="ace-icon fa fa-slack bigger-110"></i>
                            Nenhum perfil encontrado
                        </h4>
                    </div>
                </div>
            </div><!-- /.col -->
        </div>
    }

}