SESTEC/GISWeb/Controllers/AdmissaoController.cs
using GISCore.Business.Abstract;
using GISCore.Business.Concrete;
using GISModel.DTO.Shared;
using GISModel.Entidades;
using GISWeb.Infraestrutura.Filters;
using Ninject;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GISWeb.Controllers
{
    public class AdmissaoController : Controller
    {

        #region

        [Inject]
        public IAdmissaoBusiness AdmissaoBusiness { get; set; }

        [Inject]
        public IAtividadesDoEstabelecimentoBusiness AtividadesDoEstabelecimentoBusiness { get; set; }

        [Inject]
        public IDepartamentoBusiness DepartamentoBusiness { get; set; }

        [Inject]
        public IEmpresaBusiness EmpresaBusiness { get; set; }

        [Inject]
        public IEmpregadoBusiness EmpregadoBusiness { get; set; }
        [Inject]
        public IEstabelecimentoAmbienteBusiness EstabelecimentoImagensBusiness { get; set; }

        [Inject]
        public IEstabelecimentoBusiness EstabelecimentoBusiness { get; set; }

        [Inject]
        public IAtividadesDoEstabelecimentoBusiness RiscosDoEstabelecimentoBusiness { get; set; }

        [Inject]
        public IAlocacaoBusiness AlocacaoBusiness { get; set; }

        [Inject]
        public IAtividadeAlocadaBusiness AtividadeAlocadaBusiness { get; set; }

        [Inject]
        public IExposicaoBusiness ExposicaoBusiness { get; set; }

        [Inject]
        public ITipoDeRiscoBusiness TipoDeRiscoBusiness { get; set; }

        [Inject]
        public IEventoPerigosoBusiness EventoPerigosoBusiness { get; set; }


        [Inject]
        public IPossiveisDanosBusiness PossiveisDanosBusiness { get; set; }

        [Inject]
        public IPerigoPotencialBusiness PerigoPotencialBusiness { get; set; }

        #endregion



        // GET: EstabelecimentoImagens
        //public ActionResult Index(string id)
        //{

        //    ViewBag.Imagens = EstabelecimentoImagensBusiness.Consulta.Where(p => string.IsNullOrEmpty(p.UsuarioExclusao) && (p.IDEstabelecimentoImagens.Equals(id))).ToList();
        //    return View();
        //}

        public ActionResult Empresas()
        {

            ViewBag.Empresas = EmpresaBusiness.Consulta.Where(p => string.IsNullOrEmpty(p.UsuarioExclusao)).ToList();



            return View();

        }

        public ActionResult EmpregadosPorEmpresa(string idEmpresa)
        {

            ViewBag.EmpregadoPorEmpresa = AdmissaoBusiness.Consulta.Where(p => string.IsNullOrEmpty(p.UsuarioExclusao) && (p.IDEmpresa.Equals(idEmpresa))).ToList();


            return View();

        }

        //passanda IDEmpregado como parametro para montar o perfil
        public ActionResult PerfilEmpregado(string id)
        {
            ViewBag.Perfil = AdmissaoBusiness.Consulta.Where(p => string.IsNullOrEmpty(p.UsuarioExclusao) && (p.IDEmpregado.Equals(id))).ToList();
            ViewBag.Admissao = AdmissaoBusiness.Consulta.Where(p => string.IsNullOrEmpty(p.UsuarioExclusao) && (p.IDEmpregado.Equals(id))&&(p.Admitido=="Admitido")).ToList();
            ViewBag.Alocacao = AlocacaoBusiness.Consulta.Where(p => string.IsNullOrEmpty(p.UsuarioExclusao) && (p.Admissao.IDEmpregado.Equals(id)) && (p.Ativado == "true")).ToList();
            ViewBag.idEmpregado = id;

            Admissao oAdmissao = AdmissaoBusiness.Consulta.FirstOrDefault(p => p.IDEmpregado.Equals(id));




            //Esta query não deixa pegar todas as atividades se tiver exposição null
            List<Exposicao> ListaExposicao = (from ATL in AtividadeAlocadaBusiness.Consulta.Where(p => string.IsNullOrEmpty(p.UsuarioExclusao)).ToList()
                                                      join ATV in AtividadesDoEstabelecimentoBusiness.Consulta.Where(p => string.IsNullOrEmpty(p.UsuarioExclusao)).ToList()
                                                      on ATL.idAtividadesDoEstabelecimento equals ATV.IDAtividadesDoEstabelecimento
                                                        join Est in EstabelecimentoBusiness.Consulta.Where(p => string.IsNullOrEmpty(p.UsuarioExclusao)).ToList()
                                                        on ATV.IDEstabelecimento equals Est.IDEstabelecimento
                                                        join ALOC in AlocacaoBusiness.Consulta.Where(p => string.IsNullOrEmpty(p.UsuarioExclusao)).ToList()
                                                        on Est.IDEstabelecimento equals ALOC.idEstabelecimento
                                                        join EXP in ExposicaoBusiness.Consulta.Where(p => string.IsNullOrEmpty(p.UsuarioExclusao)).ToList()
                                                        on ATL.IDAtividadeAlocada equals EXP.idAtividadeAlocada
                                                        where ALOC.Admissao.IDEmpregado.Equals(id)
                                                        select new Exposicao()
                                                        {
                                                            IDExposicao = EXP.IDExposicao,
                                                            TempoEstimado = EXP.TempoEstimado,
                                                            EExposicaoCalor = EXP.EExposicaoCalor,
                                                            EExposicaoInsalubre = EXP.EExposicaoInsalubre,
                                                            EExposicaoSeg = EXP.EExposicaoSeg,
                                                            EProbabilidadeSeg = EXP.EProbabilidadeSeg,
                                                            ESeveridadeSeg = EXP.ESeveridadeSeg,


                                                            AtividadeAlocada = new AtividadeAlocada()
                                                            {
                                                                idAlocacao = ATL.idAlocacao,
                                                                idAtividadesDoEstabelecimento = ATL.idAtividadesDoEstabelecimento,
                                                                IDAtividadeAlocada = ATL.IDAtividadeAlocada,
                                                            
                                                            
                                                            AtividadesDoEstabelecimento = new AtividadesDoEstabelecimento()
                                                            {
                                                                DescricaoDestaAtividade = ATV.DescricaoDestaAtividade,

                                                                Estabelecimento = new Estabelecimento()
                                                                {
                                                                    IDEstabelecimento = Est.IDEstabelecimento,
                                                                    Descricao = Est.Descricao
                                                                }
                                                            }


                                                            }


                                                        }
                                                        ).ToList();
            ViewBag.ListaExposicao = ListaExposicao;





            List<AtividadeAlocada> ListaAtividades = (from ATL in AtividadeAlocadaBusiness.Consulta.Where(p => string.IsNullOrEmpty(p.UsuarioExclusao)).ToList()
                                                      join ATV in AtividadesDoEstabelecimentoBusiness.Consulta.Where(p => string.IsNullOrEmpty(p.UsuarioExclusao)).ToList()
                                                      on ATL.idAtividadesDoEstabelecimento equals ATV.IDAtividadesDoEstabelecimento
                                                      join ALOC in AlocacaoBusiness.Consulta.Where(p => string.IsNullOrEmpty(p.UsuarioExclusao)).ToList()
                                                      on ATL.idAlocacao equals ALOC.IDAlocacao
                                                      join ADM in AdmissaoBusiness.Consulta.Where(p => string.IsNullOrEmpty(p.UsuarioExclusao)).ToList()
                                                      on ALOC.IdAdmissao equals ADM.IDAdmissao
                                                      join Emp in EmpregadoBusiness.Consulta.Where(p => string.IsNullOrEmpty(p.UsuarioExclusao)).ToList()
                                                      on ADM.IDEmpregado equals Emp.IDEmpregado
                                                      join Est in EstabelecimentoBusiness.Consulta.Where(p => string.IsNullOrEmpty(p.UsuarioExclusao)).ToList()
                                                      on ATV.IDEstabelecimento equals Est.IDEstabelecimento                                                      
                                                      where Emp.IDEmpregado.Equals(id)
                                                      select new AtividadeAlocada()
                                                      {
                                                          idAlocacao = ATL.idAlocacao,
                                                          idAtividadesDoEstabelecimento = ATL.idAtividadesDoEstabelecimento,
                                                          IDAtividadeAlocada = ATL.IDAtividadeAlocada,

                                                          Alocacao = new Alocacao()
                                                          {
                                                              IDAlocacao = ALOC.IDAlocacao,
                                                              Admissao =new Admissao()
                                                              {
                                                                  Empregado = new Empregado()

SESTEC/GISWeb/Views/Shared/_Cabecalho.cshtml
<div id="navbar" class="navbar navbar-default navbar-fixed-top">
    <script type="text/javascript">
        try { ace.settings.check('navbar', 'fixed') } catch (e) { }
    </script>

    <div class="navbar-container" id="navbar-container">
        @if (ViewBag.OcultarMenus == null || !ViewBag.OcultarMenus)
        {
            <button type="button" class="navbar-toggle menu-toggler pull-left" id="menu-toggler" data-target="#sidebar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        }

        <div class="navbar-header pull-left align-center">
            <a href="#" class="navbar-brand EmConstrucao">
                <small>
                    @*<img src="~/Content/Images/Gedoc20_branco_150px_25px.png" />*@
                    @if (Convert.ToBoolean(System.Configuration.ConfigurationManager.AppSettings["AD:DMZ"]))
                    {
                        @*<a href="http://www.tecsesmt.com.br" target="_blank">
                            <img src="~/Content/Images/cemig_100px.png" style="width: 75%" />
                        </a>*@
                    }
                    else
                    {
                        @*<a href="http://cemignet20/" target="_blank">
                            <img src="~/Content/Images/cemig_100px.png" style="width: 75%" />
                        </a>*@
                    }
                    <span class="white">SESMT-TECNOLÓGICO</span>
                </small>
            </a>
        </div>

        @if (ViewBag.OcultarMenus == null || !ViewBag.OcultarMenus)
        {
            <div class="navbar-buttons navbar-header pull-right" role="navigation">
                <ul class="nav ace-nav">

                    @*<li class="green btnReqEmp" title="Requisição de Empréstimo" style="display: none;">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <i class="ace-icon fa fa-file-text-o"></i>
                            <span class="badge badge-success qtdItensReqEmp"></span>
                        </a>

                        <ul class="dropdown-menu-right dropdown-navbar dropdown-menu dropdown-caret dropdown-close">
                            <li class="dropdown-header">
                                <i class="ace-icon fa fa-download"></i>
                                <span class="qtdItensReqEmpLabel"></span>
                            </li>

                            <li class="dropdown-content">
                                <ul class="dropdown-menu dropdown-navbar ulReqEmp"></ul>
                            </li>

                            <li class="dropdown-footer">
                                <a href="#" onclick="FinalizarReqEmp();">
                                    Finalizar Requisição Empréstimo
                                </a>
                            </li>
                        </ul>
                    </li>*@

                    @*<li class="green" style="display: none;">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <i class="ace-icon fa fa-print"></i>
                            <span class="badge badge-success qtdItensReqCopia"></span>
                        </a>

                        <ul class="dropdown-menu-right dropdown-navbar dropdown-menu dropdown-caret dropdown-close">
                            <li class="dropdown-header">
                                <i class="ace-icon fa fa-download"></i>
                                <span class="qtdItensReqCopiaLabel"></span>
                            </li>

                            <li class="dropdown-content">
                                <ul class="dropdown-menu dropdown-navbar ulReqCopia"></ul>
                            </li>

                            <li class="dropdown-footer">
                                <a href="@Url.Action("Index", "FinalizarPedido")">
                                    Finalizar Requisição de Cópia
                                </a>
                            </li>
                        </ul>
                    </li>*@

                    <li class="light-blue">
                        <a data-toggle="dropdown" href="#" class="dropdown-toggle">
                            @if (string.IsNullOrWhiteSpace(ViewBag.NomeUsuario))
                            {
                                <img class="nav-user-photo" src="@Url.Action("FotoPerfil", "Conta")" />
                            }
                            else
                            {
                                <img class="nav-user-photo" src="@Url.Action("FotoPerfil", "Conta", new { login = ViewBag.MatriculaUsuario })" />
                            }
                            <span class="user-info">
                                <small>Bem vindo,</small>
                                <small style="font-weight: bold;">
                                    @if (string.IsNullOrWhiteSpace(ViewBag.NomeUsuario))
                                    {
                                        <span>Anônimo</span>
                                    }
                                    else
                                    {
                                        <span>@ViewBag.NomeUsuario</span>
                                    }
                                </small>
                            </span>

                            <i class="ace-icon fa fa-caret-down"></i>
                        </a>

                        <ul class="user-menu dropdown-menu-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">
                            <li>
                                <a href="@Url.Action("Perfil", "Account")">
                                    <i class="ace-icon fa fa-user"></i>
                                    Meus Dados
                                </a>
                            </li>

                            <li class="divider"></li>

                            <li>
                                <a href="@Url.Action("Sobre", "Home")">
                                    <i class="ace-icon fa fa-hashtag"></i>
                                    Sobre...
                                </a>
                            </li>

                            <li class="divider"></li>

                            <li>
                                <a href="#" data-target="#modalLogoff" data-toggle="modal">
                                    <i class="ace-icon fa fa-power-off" style="font-size: 18px"></i>
                                    Fazer logoff...
                                </a>
                            </li>
                        </ul>
                    </li>

                </ul>
            </div>
        }
    </div>
</div>

SESTEC/GISWeb/Views/Shared/_Footer.cshtml
<div class="footer hidden-480">
    <div class="footer-inner">
        <!-- #section:basics/footer -->
        <div class="footer-content" style="padding-top: 7px">
            <p>
                <span style="float: right; font-size:13px; padding-top: 2px; font-weight: 900; font-family: Arial, Helvetica, sans-serif; color: #1A1B1F">
                    @*&nbsp;&nbsp;*@SICRAM
                </span>

                <span class="action-buttons">
                    <a style="float: right">
                        @*<img src="~/Content/Images/HxGN.png" style="height: 35px" />*@
                    </a>
                </span>

                <span style="float: right; font-size:13px; padding-top: 3px; font-weight: 600; color: rgba(128, 128, 128, 0.75); font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif">
                    <i class="ace-icon fa fa-caret-right" style="color: #27A7C3"></i>&nbsp;&nbsp;SESMT-TECNOLÓGICO&#174; @System.Configuration.ConfigurationManager.AppSettings["SPF:Versao"]&nbsp;
                </span>

            </p>
        </div>
    </div>
</div>

SESTEC/GISWeb/Views/Shared/_MenuEsquerda.cshtml
@* ###########################################
    Quatro botões no menu lateral à esquerda.*@
<div class="sidebar-shortcuts" id="sidebar-shortcuts">
    <div class="sidebar-shortcuts-large" id="sidebar-shortcuts-large">
        <button class="CustomTooltip btn btn-danger btnModuloEstatistico" title="Módulo Estatístico" data-link-estatistico="@System.Configuration.ConfigurationManager.AppSettings["Web:ModuloEstatistico"]">
            <i class="ace-icon fa fa-bar-chart bigger-115"></i>
        </button>
        <button class="CustomTooltip btn btn-grey" @*data-url="@Url.Action("ACTION", "CONTROLLER")"*@>
            <i class="ace-icon fa fa-ban bigger-115"></i>
        </button>
        <button class="CustomTooltip btn btn-grey">
            <i class="ace-icon fa fa-ban bigger-115"></i>
        </button>
        <button class="CustomTooltip btn btn-grey">
            <i class="ace-icon fa fa-ban bigger-115"></i>
        </button>
    </div>

    <div class="sidebar-shortcuts-mini" id="sidebar-shortcuts-mini">
        <span class="btn btn-success"></span>
        <span class="btn btn-info"></span>
        <span class="btn btn-warning"></span>
        <span class="btn btn-danger"></span>
    </div>
</div>

<ul id="ulMenuLateral" class="nav nav-list" data-menuativo="@ViewBag.MenuAtivo">
    <li id="menuLateralPortal">
        <a href="#" class="EmConstrucao">
            <i class="menu-icon fa fa-home"></i>
            <span class="menu-text" style="font-weight: bold;">
                Portal de Colsultas
            </span>
        </a>

        <b class="arrow"></b>
    </li>
    <li id="menuLateralPesquisa">
        <a href="#" class="dropdown-toggle">
            <i class="menu-icon fa fa-search"></i>
            <span class="menu-text" style="font-weight: bold;">
                Empregado
            </span>
            <b class="arrow fa fa-angle-down"></b>
        </a>
        <b class="arrow"></b>
        <ul class="submenu">
            <li id="menuLateralPesquisaRapida">
                <a href="@Url.Action("Empresas", "Admissao")">
                    <i class="menu-icon fa fa-bolt"></i>
                    Empregado por Empresa
                </a>
                <b class="arrow"></b>
            </li>
            @*<li id="menuLateralPesquisaRapida">
                <a href="@Url.Action("EmpregadosSemAdmissao", "Empregado")">
                    <i class="menu-icon fa fa-bolt"></i>
                    Empregado sem Admissão
                </a>
                <b class="arrow"></b>
            </li>*@


        </ul>
    </li>

    <li id="menuLateralPesquisa">
        <a href="#" class="dropdown-toggle">
            <i class="menu-icon fa fa-search"></i>
            <span class="menu-text" style="font-weight: bold;">
                Estabelecimentos
            </span>
            <b class="arrow fa fa-angle-down"></b>
        </a>
        <b class="arrow"></b>
        <ul class="submenu">
            <li id="menuLateralPesquisaRapida">
                <a href="@Url.Action("Lista", "Estabelecimento")">
                    <i class="menu-icon fa fa-bolt"></i>
                    Estabelecimento
                </a>
                <b class="arrow"></b>
            </li>
            </ul>


    </li>



    <li id="menuLateralPesquisa">
        <a href="#" class="dropdown-toggle">
            <i class="menu-icon fa fa-list"></i>
            <span class="menu-text" style="font-weight: bold;">
              Menu
            </span>
            <b class="arrow fa fa-angle-down"></b>
        </a>
        <b class="arrow"></b>
        <ul class="submenu">

            <li id="menuLateralCadastro">
                <a href="#" class="dropdown-toggle">
                    <i class="menu-icon fa fa-list"></i>
                    <span class="menu-text" style="font-weight: bold;">
                        Cadastro Empregado
                    </span>
                    <b class="arrow fa fa-angle-down"></b>
                </a>
                <b class="arrow"></b>
                <ul class="submenu">
                    <li id="menuLateralPesquisaRapida">
                        <a href="@Url.Action("Novo", "Empregado")">
                            <i class="menu-icon fa fa-bolt"></i>
                            Empregado
                        </a>
                        <b class="arrow"></b>
                    </li>
                    <li id="menuLateralPesquisaRapida">
                        <a href="@Url.Action("Index", "Empregado")">
                            <i class="menu-icon fa fa-bolt"></i>
                            Empregado Admitido
                        </a>
                        <b class="arrow"></b>
                    </li>
                    <li id="menuLateralPesquisaRapida">
                        <a href="@Url.Action("BuscarEmpregado", "Empregado")">
                            <i class="menu-icon fa fa-bolt"></i>
                            Buscar Empregado
                        </a>
                        <b class="arrow"></b>
                    </li>

                </ul>
            </li>
            <li id="menuLateralCadastro">
                <a href="#" class="dropdown-toggle">
                    <i class="menu-icon fa fa-list"></i>
                    <span class="menu-text" style="font-weight: bold;">
                        Cadastro Empresas
                    </span>
                    <b class="arrow fa fa-angle-down"></b>
                </a>
                <b class="arrow"></b>
                <ul class="submenu">

                    <li id="menuLateralPesquisaRapida">
                        <a href="@Url.Action("index", "Empresa")">
                            <i class="menu-icon fa fa-bolt"></i>
                            Empresas
                        </a>
                        <b class="arrow"></b>
                    </li>
                    <li id="menuLateralPesquisaRapida">
                        <a href="@Url.Action("Index", "Diretoria")">
                            <i class="menu-icon fa fa-bolt"></i>
                            Diretoria
                        </a>
                        <b class="arrow"></b>
                    </li>
                    <li id="menuLateralPesquisaRapida">
                        <a href="@Url.Action("Index", "Estabelecimento")">
                            <i class="menu-icon fa fa-bolt"></i>
                            Estabelecimentos
                        </a>
                        <b class="arrow"></b>
                    </li>

                    <li id="menuLateralPesquisaRapida">
                        <a href="@Url.Action("Index", "Departamento")">
                            <i class="menu-icon fa fa-bolt"></i>
                            Departamento
                        </a>
                        <b class="arrow"></b>
                    </li>
                    <li id="menuLateralPesquisaRapida">
                        <a href="@Url.Action("Index", "TipoDeRisco")">
                            <i class="menu-icon fa fa-bolt"></i>
                            Tipo de Risco
                        </a>
                        <b class="arrow"></b>
                    </li>
                    <li id="menuLateralPesquisaRapida">
                        <a href="@Url.Action("Index", "PlanoDeAcao")">
                            <i class="menu-icon fa fa-bolt"></i>
                            Plano de Ação
                        </a>
                        <b class="arrow"></b>
                    </li>
                    <li id="menuLateralPesquisaRapida">
                        <a href="@Url.Action("Index", "Cargo")">
                            <i class="menu-icon fa fa-bolt"></i>
                            Cargo
                        </a>
                        <b class="arrow"></b>
                    </li>
                    <li id="menuLateralPesquisaRapida">
                        <a href="@Url.Action("Index", "Funcao")">
                            <i class="menu-icon fa fa-bolt"></i>
                            Função
                        </a>
                        <b class="arrow"></b>
                    </li>

                    <li id="menuLateralPesquisaRapida">
                        <a href="@Url.Action("Index", "Admissao")">
                            <i class="menu-icon fa fa-bolt"></i>
                            Admissao
                        </a>
                        <b class="arrow"></b>
                    </li>
                    <li id="menuLateralPesquisaRapida">
                        <a href="@Url.Action("Index", "EventoPerigoso")">
                            <i class="menu-icon fa fa-bolt"></i>
                            Evento Perigoso
                        </a>
                        <b class="arrow"></b>
                    </li>
                    <li id="menuLateralPesquisaRapida">
                        <a href="@Url.Action("Index", "TipoDeRisco")">
                            <i class="menu-icon fa fa-bolt"></i>
                            Tipos de Perigos
                        </a>
                        <b class="arrow"></b>
                    </li>
                    <li id="menuLateralPesquisaRapida">
                        <a href="@Url.Action("Index", "PossiveisDanos")">
                            <i class="menu-icon fa fa-bolt"></i>
                            Possiveis Danos
                        </a>
                        <b class="arrow"></b>
                    </li>
                    <li id="menuLateralPesquisaRapida">
                        <a href="@Url.Action("Index", "Atividade")">
                            <i class="menu-icon fa fa-bolt"></i>
                            Atividades
                        </a>
                        <b class="arrow"></b>
                    </li>
                    <li id="menuLateralPesquisaRapida">
                        <a href="@Url.Action("Index", "AtividadeRiscos")">
                            <i class="menu-icon fa fa-bolt"></i>
                            Atividades de Risco
                        </a>
                        <b class="arrow"></b>
                    </li>
                    <li id="menuLateralPesquisaRapida">
                        <a href="@Url.Action("Index", "Contrato")">
                            <i class="menu-icon fa fa-bolt"></i>
                            Contratos
                        </a>
                        <b class="arrow"></b>
                    </li>
                    @*<li id="menuLateralPesquisaAvancada">
            <a href="#" class="dropdown-toggle">
                <i class="menu-icon fa fa-caret-right"></i>
                Avançada
                <b class="arrow fa fa-angle-down"></b>
            </a>
            <b class="arrow"></b>
            <ul class="submenu">

                <li id="liTeste">
                    <a href="#">
                        Usuário
                    </a>
                    <b class="arrow"></b>
                </li>

            </ul>
        </li>*@
                </ul>
                </li>
            </li>

            @*@if (ViewBag.IsAdministrador)
        {*@
            @*<li id="menuLateralAdministracao">
            <a href="@Url.Action("")">
                <i class="menu-icon fa fa-gears"></i>
                <span class="menu-text" style="font-weight: bold;">
                    Administração
                </span>
                <b class="arrow"></b>
            </a>
        </li>*@
            @*}*@

            @*<li id="menuLateralMeusPedidos">
            <a href="#" class="dropdown-toggle">
                <i class="menu-icon fa fa-shopping-cart"></i>
                <span class="menu-text" style="font-weight: bold;">
                    Meus Pedidos
                </span>
                <b class="arrow fa fa-angle-down"></b>
            </a>
            <b class="arrow"></b>
            <ul class="submenu">
                <li id="subMenuPedidosEmprestimo">
                    <a href="@Url.Action("Index", "MeusPedidos", new { tipo = "emprestimo" })">
                        <i class="menu-icon fa fa-bolt"></i>
                        Pedidos de Empréstimo
                    </a>
                    <b class="arrow"></b>
                </li>
                <li id="subMenuPedidosCopia">
                    <a href="@Url.Action("Index", "MeusPedidos", new { tipo = "copia" })">
                        <i class="menu-icon fa fa-bolt"></i>
                        Pedidos de Cópia
                    </a>
                    <b class="arrow"></b>
                </li>
            </ul>
        </li>*@

        </ul>

        <div class="sidebar-toggle sidebar-collapse" id="sidebar-collapse">
            <i class="ace-icon fa fa-angle-double-left" data-icon1="ace-icon fa fa-angle-double-left" data-icon2="ace-icon fa fa-angle-double-right"></i>
        </div>