SESTEC/GISWeb/Controllers/AlocacaoController.cs
using GISCore.Business.Abstract;
using GISModel.DTO.Shared;
using GISModel.Entidades;
using Ninject;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GISWeb.Controllers
{
    public class AlocacaoController : Controller
    {

        #region


        

        [Inject]
        public ITipoDeRiscoBusiness TipoDeRiscoBusiness { get; set; }

        [Inject]
        public IAtividadeBusiness AtividadeBusiness { get; set; }

        //[Inject]
        //public IExposicaoBusiness ExposicaoBusiness { get; set; }

        [Inject]
        public IEquipeBusiness EquipeBusiness { get; set; }

        [Inject]
        public IFuncaoBusiness FuncaoBusiness { get; set; }
        [Inject]
        public ICargoBusiness CargoBusiness { get; set; }
        [Inject]
        public IContratoBusiness ContratoBusiness { get; set; }

        [Inject]
        public IAlocacaoBusiness AlocacaoBusiness { get; set; }
        [Inject]
        public IAdmissaoBusiness AdmissaoBusiness { get; set; }

        [Inject]
        public IDepartamentoBusiness DepartamentoBusiness { get; set; }


        [Inject]
        public IEmpresaBusiness EmpresaBusiness { get; set; }

        [Inject]
        public IEmpregadoBusiness EmpregadoBusiness { get; set; }

        [Inject]
        public IEstabelecimentoBusiness EstabelecimentoBusiness { get; set; }

        [Inject]
        public IAtividadesDoEstabelecimentoBusiness AtividadesDoEstabelecimentoBusiness { get; set; }

        [Inject]
        public IMedidasDeControleBusiness MedidasDeControleBusiness { get; set; }

        [Inject]
        public IEstabelecimentoAmbienteBusiness EstabelecimentoAmbienteBusiness { get; set; }

        //[Inject]
        //public IAlocacaoAtividadesBusiness AlocacaoAtividadesBusiness { get; set; }

        //[Inject]
        //public IAtividadeRiscosBusiness AtividadeRiscosBusiness { get; set; }

        #endregion



        // GET: Alocacao
        public ActionResult Index()
        {
            return View();
        }
        
        public ActionResult Novo(string IDAdmissao,string IDEmpregado,string IDEmpresa)
        {

            ViewBag.Equipe = new SelectList(EquipeBusiness.Consulta.Where(p => string.IsNullOrEmpty(p.UsuarioExclusao)).ToList(), "IDEquipe", "NomeDaEquipe");
            ViewBag.pAdmissao = IDAdmissao;
            ViewBag.pEmpregado = IDEmpregado;
            ViewBag.Admissao = AdmissaoBusiness.Consulta.Where(p => string.IsNullOrEmpty(p.UsuarioExclusao)&& p.IDAdmissao.Equals(IDAdmissao) ).ToList();
            ViewBag.Contrato = new SelectList(ContratoBusiness.Consulta.Where(p => string.IsNullOrEmpty(p.UsuarioExclusao)).ToList(), "IDContrato", "NumeroContrato");
            ViewBag.Departamento = new SelectList(DepartamentoBusiness.Consulta.ToList(), "IDDepartamento", "Sigla");
            ViewBag.Cargo = new SelectList(CargoBusiness.Consulta.Where(p => string.IsNullOrEmpty(p.UsuarioExclusao)).ToList(), "IDCargo", "NomeDoCargo");
            ViewBag.Funcao = new SelectList(FuncaoBusiness.Consulta.Where(p => string.IsNullOrEmpty(p.UsuarioExclusao)).ToList(), "IDFuncao", "NomeDaFuncao");
            ViewBag.Estabelecimento = new SelectList(EstabelecimentoBusiness.Consulta.Where(p => string.IsNullOrEmpty(p.UsuarioExclusao)).ToList(), "IDEstabelecimento", "NomeCompleto");


            try
            {
                Admissao oAdmissao = AdmissaoBusiness.Consulta.FirstOrDefault(p => p.IDEmpregado.Equals(IDAdmissao));
                if (ViewBag.Admissao == null)
                {
                    return Json(new { resultado = new RetornoJSON() { Alerta = "Imagens não encontrada." } });
                }
                else
                {
                    return Json(new { data = RenderRazorViewToString("_Novo", oAdmissao) });
                }
            }
            catch (Exception ex)
            {
                if (ex.GetBaseException() == null)
                {
                    return Json(new { resultado = new RetornoJSON() { Erro = ex.Message } });
                }
                else
                {
                    return Json(new { resultado = new RetornoJSON() { Erro = ex.GetBaseException().Message } });
                }
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Cadastrar(Alocacao oAlocacao, string IDAdmissao, string IDEmpregado)
        {

            //id da Admissão recebido por parametro
            oAlocacao.IdAdmissao = IDAdmissao;
           
            if (ModelState.IsValid)
            {
                try
                {

                    AlocacaoBusiness.Inserir(oAlocacao);

                    TempData["MensagemSucesso"] = "O empregado foi Alocado com sucesso.";

                    
                    //precisa passa o id do Empregado
                    return Json(new { resultado = new RetornoJSON() { URL = Url.Action("PerfilEmpregado", "Admissao", new { id = IDEmpregado }) } });


                }
                catch (Exception ex)
                {
                    if (ex.GetBaseException() == null)
                    {
                        return Json(new { resultado = new RetornoJSON() { Erro = ex.Message } });
                    }
                    else
                    {
                        return Json(new { resultado = new RetornoJSON() { Erro = ex.GetBaseException().Message } });
                    }
                }

            }
            else
            {
                return Json(new { resultado = TratarRetornoValidacaoToJSON() });
            }
        }




        [HttpPost]
        public ActionResult TerminarComRedirect(string idAlocacao,string idEmpregado)
        {

            try
            {
                Alocacao oAlocacao = AlocacaoBusiness.Consulta.FirstOrDefault(p => p.IDAlocacao.Equals(idAlocacao));
                if (oAlocacao == null)
                {
                    return Json(new { resultado = new RetornoJSON() { Erro = "Não foi possível Desalocar este empregado!" } });
                }
                else
                {
                    oAlocacao.DataExclusao = DateTime.Now;
                    oAlocacao.UsuarioExclusao = "LoginTeste";
                    oAlocacao.Ativado = "false";
                    AlocacaoBusiness.Alterar(oAlocacao);

                    TempData["MensagemSucesso"] = "O Empregado '" + oAlocacao.Admissao.Empregado.Nome + "' foi desalocado com sucesso.";

                    return Json(new { resultado = new RetornoJSON() { URL = Url.Action("PerfilEmpregado", "Admissao", new { id = idEmpregado }) } });
                }
            }
            catch (Exception ex)
            {
                if (ex.GetBaseException() == null)
                {
                    return Json(new { resultado = new RetornoJSON() { Erro = ex.Message } });
                }
                else
                {
                    return Json(new { resultado = new RetornoJSON() { Erro = ex.GetBaseException().Message } });
                }
            }


        }






        private string RenderRazorViewToString(string viewName, object model = null)
        {
            ViewData.Model = model;
            using (var sw = new System.IO.StringWriter())
            {
                var viewResult = ViewEngines.Engines.FindPartialView(ControllerContext,
                                                                         viewName);
                var viewContext = new ViewContext(ControllerContext, viewResult.View,
                                             ViewData, TempData, sw);
                viewResult.View.Render(viewContext, sw);
                viewResult.ViewEngine.ReleaseView(ControllerContext, viewResult.View);
                return sw.GetStringBuilder().ToString();
            }
        }

        public RetornoJSON TratarRetornoValidacaoToJSON()
        {


            string msgAlerta = string.Empty;
            foreach (ModelState item in ModelState.Values)
            {
                if (item.Errors.Count > 0)
                {
                    foreach (System.Web.Mvc.ModelError i in item.Errors)
                    {
                        msgAlerta += i.ErrorMessage;
                    }
                }
            }

            return new RetornoJSON()
            {
                Alerta = msgAlerta,
                Erro = string.Empty,
                Sucesso = string.Empty
            };

        }

    }




}

SESTEC/GISWeb/Views/Alocacao/_Novo.cshtml
@*@model GISModel.Entidades.Alocacao*@



@{
    ViewBag.Title = "Novo";
}


@model GISModel.Entidades.Alocacao

@{
    ViewBag.Title = "Alocação do Empregado";
}

@{
    Html.RenderPartial("_MensagensDeRetorno");
}

@foreach (var iAdmissao in ViewBag.Admissao)
{
    <i class="material-icons" style="font-size:36px;color:blue">@iAdmissao.Empregado.Nome&nbsp @iAdmissao.Empregado.CPF</i>


    <tr id="linha-@iAdmissao.IDAdmissao">

        <div class="row">
            <div class="col-xs-12 col-sm-2">
                <div class="form-group">

                    <td>
                        <img src="/Images/AdmissaoImagens/@iAdmissao.IDAdmissao/@iAdmissao.Imagem" alt="Admissao" width="100px" />
                    </td>
                </div>
            </div>

            <div class="col-xs-12 col-sm-10">
                <div class="form-group">
                    <td>
                        <b>

                            <i class="fa fa-arrows-alt" style="font-size:18px"><i class="material-icons" style="font-size:18px;color:red">Empresa:</i>@iAdmissao.Empresa.NomeFantasia</i>
                            <br />

                            <i class="fa fa-arrows-alt" style="font-size:18px"><i class="material-icons" style="font-size:18px;color:red">Email:</i>@iAdmissao.Empregado.Email</i>
                            <br />

                            <i class="fa fa-arrows-alt" style="font-size:18px"><i class="material-icons" style="font-size:18px;color:red">Data de Nascimento:</i>@iAdmissao.Empregado.DataNascimento</i>
                            <br />

                            <i class="fa fa-arrows-alt" style="font-size:18px"><i class="material-icons" style="font-size:18px;color:red">Data de Admissão:</i>@iAdmissao.DataAdmissao</i>
                            <br />

                            <i class="fa fa-arrows-alt" style="font-size:18px"><i class="material-icons" style="font-size:18px;color:red">Admitido por:</i>@iAdmissao.UsuarioInclusao</i>
                        </b>
                    </td>
                </div>
            </div>
        </div>



    </tr>

}


@using (Ajax.BeginForm("Cadastrar", "Alocacao", null, new AjaxOptions { HttpMethod = "POST", OnBegin = "OnBeginCadastrarAlocacao", OnSuccess = "OnSuccessCadastrarAlocacao", }, new { @id = "formCadastroAlocacao", @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()

    

    <div class="row">

        <div class="col-xs-12 col-sm-4">
            <div class="form-group">
                @Html.LabelFor(d => d.Contrato, new { @class = "form-field-select-3 col-xs-12 col-sm-6 no-padding-right" })
                <div class="col-xs-12 col-sm-12">
                    @Html.DropDownListFor(d => d.IdContrato, (SelectList)ViewBag.Contrato, "Selecione um Contrato...", new { @class = "chosen-select form-control tag-input-style", @id = "ddlContrato", @autocomplete = "on" })
                    @Html.ValidationMessageFor(d => d.IdContrato, string.Empty, new { @style = "font-size: 10px; color: #a94442;" })
                    <input type="text" name="IDAdmissao" id="IDAdmissao" value=@ViewBag.pAdmissao hidden />
                    <input type="text" name="IDEmpregado" id="IDEmpregado" value=@ViewBag.pEmpregado hidden />
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-sm-4">
            <div class="form-group">
                @Html.LabelFor(d => d.IDDepartamento, new { @class = "form-field-select-3 col-xs-12 col-sm-6 no-padding-right" })
                <div class="col-xs-12 col-sm-12">
                    @Html.DropDownListFor(d => d.IDDepartamento, (SelectList)ViewBag.Departamento, "Selecione um Departamento...", new { @class = "chosen-select form-control tag-input-style", @id = "ddlDepartamento", @autocomplete = "on" })
                    @Html.ValidationMessageFor(d => d.IDDepartamento, string.Empty, new { @style = "font-size: 10px; color: #a94442;" })
                                       
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-sm-4">
            <div class="form-group">
                @Html.Label("Cargo", new { @class = "form-field-select-3 col-xs-12 col-sm-6 no-padding-right" })
                <div class="col-xs-12 col-sm-12">
                    @Html.DropDownListFor(d => d.IDCargo, (SelectList)ViewBag.Cargo, "Selecione um Cargo...", new { @class = "chosen-select form-control tag-input-style", @id = "ddlDepartamento", @autocomplete = "on" })
                    @Html.ValidationMessageFor(d => d.IDCargo, string.Empty, new { @style = "font-size: 10px; color: #a94442;" })
                                       
                </div>
            </div>
        </div>

    </div>
    <div class="row">

        <div class="col-xs-12 col-sm-4">
            <div class="form-group">
                @Html.Label("Função", new { @class = "form-field-select-3 col-xs-12 col-sm-6 no-padding-right" })
                <div class="col-xs-12 col-sm-12">
                    @Html.DropDownListFor(d => d.IDFuncao, (SelectList)ViewBag.Funcao, "Selecione uma Função...", new { @class = "chosen-select form-control tag-input-style", @id = "ddlDepartamento", @autocomplete = "on" })
                    @Html.ValidationMessageFor(d => d.IDFuncao, string.Empty, new { @style = "font-size: 10px; color: #a94442;" })

                </div>
            </div>
        </div>
        <div class="col-xs-12 col-sm-4">
            <div class="form-group">
                @Html.LabelFor(d => d.idEstabelecimento, new { @class = "form-field-select-3 col-xs-12 col-sm-6 no-padding-right" })
                <div class="col-xs-12 col-sm-12">
                    @Html.DropDownListFor(d => d.idEstabelecimento, (SelectList)ViewBag.Estabelecimento, "Selecione um Estabelecimento...", new { @class = "chosen-select form-control tag-input-style", @id = "ddlDepartamento", @autocomplete = "on" })
                    @Html.ValidationMessageFor(d => d.idEstabelecimento, string.Empty, new { @style = "font-size: 10px; color: #a94442;" })

                </div>
            </div>
        </div>
        <div class="col-xs-12 col-sm-4">
            <div class="form-group">
                @Html.LabelFor(d => d.IDEquipe, new { @class = "form-field-select-3 col-xs-12 col-sm-6 no-padding-right" })
                <div class="col-xs-12 col-sm-12">
                    @Html.DropDownListFor(d => d.IDEquipe, (SelectList)ViewBag.Equipe, "Selecione uma Equipe...", new { @class = "chosen-select form-control tag-input-style", @id = "ddlEquipe", @autocomplete = "on" })
                    @Html.ValidationMessageFor(d => d.IDEquipe, string.Empty, new { @style = "font-size: 10px; color: #a94442;" })

                </div>
            </div>
        </div>





    </div>


        <div class="row">
            <div class="col-xs-12 col-sm-6 col-sm-offset-3 align-center">
                <button class="btn btn-info" id="btnSalvar" type="submit">
                    <i class="ace-icon fa fa-check bigger-110"></i>
                    Salvar
                </button>
                @*&nbsp;
                <button class="btn btn-warning" type="reset">
                    <i class="ace-icon fa fa-undo bigger-110"></i>
                    Limpar
                </button>
                &nbsp;*@
                <a class="btn" href="javascript:history.back()">
                    <i class="ace-icon fa fa-arrow-left"></i>
                    Voltar
                </a>
            </div>
        </div>
        }